CREATE TABLE "account"
(
    "id"       BIGINT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "login"    VARCHAR,
    "password" VARCHAR,
    "balance"  numeric(10, 2) NOT NULL DEFAULT 0,
    CONSTRAINT "account_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "login_unique" UNIQUE ("login")
)